### ISSUE TITLE
Issue with hoverable dropdown on mobile

### ISSUE THREAD

**Issue by deepwriter** [foundation/foundation-sites#10730]
The hover drop down does not close on click on mobile devices.

If I click the dropdown it opens and if I click the body it closes but not on drop down click. Initially I thought the problem was my code but I noticed this issue occurs on the foundation docs page as well https://foundation.zurb.com/sites/docs/dropdown.html

I'm using 6.3

**Comment by SassNinja** [comment]
@deepwriter thanks for reporting this.

But in may eyes it's not a bug but the expected behavior.

On a mobile device a touch event is considered as hover since there's no mouse.
Thus clicking the dropdown several times is preserving the hover state and keeping the pane opened. The same happens on desktop if you move your mouse over hoverable dropdown button and click several times.

If you doesn't want the hoverable button on mobile devices I'd suggest to duplicate it (without the option set true) and use the visibility classes.

**Comment by vcarneiro** [comment]
Rather than having duplicate dropdown panes one of hover and one for click. Is it possible to update the one dropdown pane to accommodate both hover and click? Maybe by using screen size or whatinput?

**Comment by DanielRuf** [comment]
See https://github.com/foundation/foundation-sites/pull/11430

**Comment by joeworkman** [comment]
This issue has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/dropdown-container-not-closing-on-touch/2399/5
