### ISSUE TITLE
DOCS Conflicting browser support info on Grid

### ISSUE THREAD

**Issue by christopherdarling** [foundation/foundation-sites#11617]
## Description
[XY Grid](https://foundation.zurb.com/sites/docs/xy-grid.html) says that it supports IE10
[Float Grid](https://foundation.zurb.com/sites/docs/grid.html) and [Flex Grid](https://foundation.zurb.com/sites/docs/flex-grid.html) both state "Unless you need to support IE 10, it is recommended to use the XY Grid." 

## Possible Solution
Either XY Grid doesn't support IE 10, or the recommendation to not use XY Grid unless IE 10 support is needed should say IE 9?

## Checklist
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by ncoden** [comment]
The XY Grid is partially supported by IE10, due to the amount of bug present with flexboxs. Most simple features works, but it is recommended to use the Float/Flex grid if you need to fully support IE10.

I'll make some tests but we may have to update the XY Grid documentation to "The XY grid is supported in (...) IE11".
