### ISSUE TITLE
Throttle helper missing from Foundation 6 documentation

### ISSUE THREAD

**Issue by rbrlortie** [foundation/foundation-sites#11718]
## Description
Foundation still exposes it's throttle/debounce helper `Foundation.util.throttle`. This fact is not written in the documentation.

It was on:

https://foundation.zurb.com/sites/docs/v/5.5.3/javascript-utilities.html#delay

But now it seems missing from:

https://foundation.zurb.com/sites/docs/javascript-utilities.html

## Possible Solution
Since it works almost the same, we could copy the content from the previous documentation.

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
https://github.com/zurb/foundation-sites/blob/36fd87851f8975ea26618291777fc180ff564252/js/foundation.core.js#L230

https://github.com/zurb/foundation-sites/blob/develop/docs/pages/javascript-utilities.md

https://github.com/zurb/foundation-sites/blob/v5.5.3/doc/pages/javascript-utilities.html#L111-L182

Seems to be missing since 6.0.0: https://github.com/zurb/foundation-sites/blob/v6.0.0/docs/pages/javascript-utilities.md

**Comment by DanielRuf** [comment]
Hi @rbrlortie 👋 

thanks for reporting this.

I'm adding some more infos for us so we can copy the needed information.

https://github.com/zurb/foundation-sites/blob/36fd87851f8975ea26618291777fc180ff564252/js/foundation.core.js#L230

https://github.com/zurb/foundation-sites/blob/develop/docs/pages/javascript-utilities.md

https://github.com/zurb/foundation-sites/blob/v5.5.3/doc/pages/javascript-utilities.html#L111-L182

Seems to be missing since 6.0.0: https://github.com/zurb/foundation-sites/blob/v6.0.0/docs/pages/javascript-utilities.md

**Comment by evagm** [comment]
👋 from Hacktoberfest! I've reintroduced the throttle into the docs but my commit message seems to be invalid. I have look at the contributing guidelines and other commits on the project and I'm at a bit of a loss. Am I missing something?

`docs: reintroduce throttle debounce helper (#11718)`

**Comment by DanielRuf** [comment]
Hi @evagm ,

Thanks for your contribution.

Can you use `--no-verify`? I will check your PR then.
