### ISSUE TITLE
Is Zurb Foundation in active development?

### ISSUE THREAD

**Issue by bgarrant** [foundation/foundation-sites#11767]
I have not seen a new pull request go through since Jan 2019.  Is Foundation still in active development?  I just want to know before I use on a few new projects.

Thanks in advance.

**Comment by DanielRuf** [comment]
I was one of the most active contributors to Foundation Sites in the last years. I'll try to answer this as best as possible.

In general this project is maintained and developed by volunteers, there are not so many people from ZURB involved anymore (which is not great). The communication could have been better.

The lead dev which helped with the last releases left the project and works on other things now. Currently I am mostly the solely active contributor. Unfortunately I (still) see no active contributions from other Yetinauts (the volunteers).

Doing this alone is not very motivating and the motivation which I had for Foundation Sites is not there anymore and I have stopped investing more time.

I welcome any help from the community and invite you all to actively contribute to the code.
So far 8 people have reacted to this issue and almost all have never contributed to this project (well, maintaining something big like this is a big responsibility and being a maintainer is never easy). This is not a critic but I would like to get some support by others.

**Comment by reinhardmohr** [comment]
Hi, Daniel,
thanks for helping so much!
This is the first clear answer about the progress of Foundation since I thought something might have gone wrong. I am no developer (at least not a real one) so I can't really help maintain the code. But what else could people like me do? People who have used Foundation, benefitted from it and would now like to give back something?
Could we develop a plan, an idea, a suggestion?
Thanks for helping and maintaining
Reinhard

**Comment by bgarrant** [comment]
Thanks for the work you have done Daniel. I am not a developer either so there is not much I can offer.  Sorry.  I hope Foundation lives on.

**Comment by oliviertassinari** [comment]
https://www.rank2traffic.com/zurb.com might provide a global context.

**Comment by DanielRuf** [comment]
@oliviertassinari context for what? This does not change anything on our side tbh.

**Comment by oliviertassinari** [comment]
There is an opportunity cost in anything we undertake. I hope this data will help you best leverage your time.

**Comment by matteotestoni** [comment]
Where is ncoden?

**Comment by JeremyEnglert** [comment]
> Where are ncoden Rafi and others?

- Ncoden is working on other project.
- Rafi works for ZURB. Not 100% sure.
- Others? We're all volunteers. So everyone has their own projects to work on. Without a "lead", the project lost momentum.

**Comment by brettsmason** [comment]
A lot of us are still around. But unfortunately without any clear direction or lead, my motivation to help just isn't there.

**Comment by reinhardmohr** [comment]
Hi, I am neither a coder nor a Yetinaut – I am just an ordinary user of Fundation. But I regret it being abandoned.
So: 

- How could things be organized?
- How could I help?
- What could we do to maintain the project?
- Who could and should discuss things with Zurb?

Given there are 100 users of Foundation each willing to give a 100 Dollars to keep the project going (I am willing to): There would be 10.000 Dollars as a starting point …

How could things be started to improve?

Thanks for answering and helping

Reinhard

**Comment by xgarb** [comment]
Maybe a Kickstarter for a JQuery-free version 7?

**Comment by matteotestoni** [comment]
As a web developer my priorities are different. 
- fix for problems with topbar menu
- fix for sticky
- fix for usability: topmenu for smartphone, 
- use media queries like bootstrap
- responsive font sizes
...
..

Things like this. If there is jquery or not for me is not important. 
If development of a version without jquery is too expensive i think is not a priority

Matteo

**Comment by DanielRuf** [comment]
> responsive font sizes

I guess you mean CSS Locks. See https://css-tricks.com/math-css-locks/

> use media queries like bootstrap

Not sure what you mean.

**Comment by SassNinja** [comment]
> > use media queries like bootstrap
>
> Not sure what you mean.

I'm wondering the same. What exactly do you mean?
Foundation provides breakpoint specific classes, too.

**Comment by JeremyEnglert** [comment]
> Given there are 100 users of Foundation each willing to give a 100 Dollars to keep the project going (I am willing to): There would be 10.000 Dollars as a starting point …

That's a great goal, but I'm also not sure how realistic it is. Even if $10,000 was raised, I'm not sure how long that could keep someone/people working on the project. When Foundation was at its peak, it had multiple (ZURB) developers investing a ton of time into it.

> How could things be started to improve?

Direction. Someone from ZURB needs to step up and lead the project or help the project cut ties from ZURB and become completely community based. At the moment, not much can be done without ZURB's input.



> Maybe a Kickstarter for a JQuery-free version 7?

A "jQuery Free" version isn't going to save the project. A Kickstarter might be a good idea, but we can build a campaign around specific features (jQuery-free).

> As a web developer my priorities are different....If development of a version without jquery is too expensive i think is not a priority

Honestly, at this point there isn't even enough resources to maintain V6. It's not about funds (although that helps) or priorities. It's a lack of direction and time that is the issue.

**Comment by Sven-WEBDESIGN** [comment]
Hello Daniel, first, thanks for your work in a difficult context, second, i am sorry that i hear this only now.
For a very long time, Foundation has been for me the number 1 framework, for is quality, thoroughness and solidity.
So, i'd guess the community has to communicate clearly toward ZURB and itself to gain clarity as to who is responsible for what and in what directions. You can't go on like this and ZURB should take position clearly, as clearly as they can at least. Abandonning a project is always hard but the worst is letting this community and product down without telling it.
Daniel, would you know how to communicate officially  with ZURB? I'd be willing to ask them, again if it was asked already, to position themselves. I think it's the main point, cause infrastructure and project maintenance is hard, it's a very large project already, and it's technical both in what it delivers and how it's delivered (tooling for making the source compile, ...)

**Comment by JeremyEnglert** [comment]
> Daniel, would you know how to communicate officially with ZURB? I'd be willing to ask them, again if it was asked already, to position themselves. I think it's the main point, cause infrastructure and project maintenance is hard, it's a very large project already, and it's technical both in what it delivers and how it delivers it (tooling for making the source compile, ...)
> 
> Let's ask ZURB (once again?) to tell where they're going, their involvement, the reasons perhaps behind, seemingly, this letting down of the project and its community.

There's a slack channel where Yetinauts (core contributors) and ZURB communicate. The concerns everyone has been raising here have been mentioned.

**Comment by Sven-WEBDESIGN** [comment]
Hello @JeremyEnglert or @DanielRuf , thanks for your precisions, i had the feeling it had been asked but was not sure. Would you know if the slack channnel is public or closed (from what you tell me it's closed except for core contributors) and if it's public, the slack channel name?

**Comment by SassNinja** [comment]
@Sven-WEBDESIGN it's a closed channel (core contributors only)

**Comment by Sven-WEBDESIGN** [comment]
@SassNinja, thanks, i'll try another way then.

**Comment by dlewand691** [comment]
I'm so sad to read all of this. I've been using Foundation since the beginning and I pushed my team to use it on cognizant.com. Like others, I'm a user but not a developer but would like to get involved however I can. 

If Zurb has no interest in maintaining Foundation anymore, then who would be willing to take it over? And is the project roadmap still applicable? [https://github.com/zurb/foundation-sites/wiki/Project-Roadmap](https://github.com/zurb/foundation-sites/wiki/Project-Roadmap)

Don't let the Yeti die!

**Comment by JeremyEnglert** [comment]
> If Zurb has no interest in maintaining Foundation anymore, then who would be willing to take it over? And is the project roadmap still applicable? https://github.com/zurb/foundation-sites/wiki/Project-Roadmap

Probably not. The ideas are valid, but the timing isn't realistic at this point.

**Comment by reinhardmohr** [comment]
I have tried to find out what is going on with Foundation for half a year. And there were no clear signs. Now I have found this thread and I am following it for two weeks. And finally I get some information.
But it seems we are all sitting around, waiting for something to happen. Or waiting for someone to lead.
Couldn't we start something  to initiate a rescue process? E.g. build up a website like "rescue-foundation.org"? Or inform companies who rely on Foundation as a part of their own products (like pinegrow.com or coffeecup.com) if they are willing to take over the project?
Or could anyone here who is envolved set up a roadmap for rescue and publish it here?
How do we start?

Thanks for your ongoing contributions
Reinhard

**Comment by dlewand691** [comment]
That's a good point about apps like Pinegrow and CoffeeCup. They have a vested interest in it already so maybe they would have some ideas or leverage? 

Has anyone reached out to former Zurb folks like K-ball or Rafi? Maybe they have some insight?

**Comment by dlewand691** [comment]
Hi all-
I reached out to KBall on Twitter and this is our conversation. Seems @JeremyEnglert is correct when he said it's about leadership and direction. Who runs Zurb or their dev team? Can we reach out to them? Thousands of people rely on/use Foundation so just disappearing with no notice reflects pretty poorly on Zurb overall. 

> KBall! Seems that Foundation is dying...it hasn't been updated since January and nobody from Zurb will respond. Any ideas on who we might contact? Don't let the Yeti die!

 
 > KBall
 Hi Daniel! Thanks for reaching out. Yes it definitely feels like Foundation is dying... there are some people trying to get it out of ZURB & keep it alive, but it has been slow and ZURB while in theory in favor in practice has been very slow moving.

>Jun 24
 KBall
 Some folks you might reach out to who are trying to move things along/organize are Jeremy Englert (@JeremyEnglert) and Joe Workman (@joeworkman)

> Jun 24
 Daniel Lewandowski
 That's too bad! It's been my go-to framework since the beginning. Any reason why? I'm sure it's a lot to manage. Thanks for the contacts, I'll reach out soon. Thank you, sir!

 
 > KBall
 Main reason why is ZURB is no longer investing resources in it, but has not succeeded in truly releasing it to the community. ZURB stopped investing about 2 years ago when they had acute financial problems and laid off 1/3 of the company (including me). My sense from talking to some folks who are still there is it is no longer quite as dire but still very tight and everyone there is overworked, so not very responsive on things that are no longer in their main work

> Jun 24
 Daniel Lewandowski
 Makes sense from a business standpoint. They've got to focus on paying clients and not side projects. But it does reflect poorly on them when thousands of people use a product and then everything stops. Preaching to the choir, I know. Sucks to go through that, I've been there a few times myself. Hope you landed somewhere good and are doing well.

**Comment by joeworkman** [comment]
@kball is correct. I am working with the team at Zurb on formulating a plan to fully transition the Foundation framework over to the community. I will be heading into their offices next week in hopes that we can push things a little faster while in person. 

I love Foundation and definitely want to make sure that it and all of its users are taken care of.

**Comment by Sven-WEBDESIGN** [comment]
@dlewand691, @kball, @joeworkman, thank you all for reaching out and responding.
@joeworkman, could use this thread till your next steps are more clear regarding foundation ar Zurb? So that we have a unique entrypoint to follow.

**Comment by dlewand691** [comment]
Hi all-
I emailed Zurb and heard back from Rafi and Shawna Moser. Seems that things have stalled but they're planning to ramp them back up again. 

From Rafi:
> We have a plan for Foundation that has stalled in the past but we're ramping it up again. It definitely involves community ownership and a strong core team.

From Shawna: 
> We're happy to say that Foundation isn't dead and like you mentioned, the Yeti has been hibernating while we're developing Helio.app. 

The Yeti will live to see another day!

**Comment by rafibomb** [comment]
All of the above is true, the good and the bad. We love Foundation AND **we love that so many people care**. We (ZURB) still use Foundation on our product Helio (https://helio.app/) which is an Angular + Foundation build as well of all our client projects we deliver.

We have a plan to transition Foundation over to the community and separate the ZURB name because we can no longer invest in it as a company. For so many reasons, this process which started in January 2019 has stalled. We don't want to just cut the ZURB name off and say bye. There needs to be a strong, official, foundation of leadership and direction to make this work.

We believe the project will be even stronger in your hands. In the meantime we need to continue finding bugs, fixing bugs, and providing opinions.

**Comment by Sven-WEBDESIGN** [comment]
> I have not seen a new pull request go through since Jan 2019. Is Foundation still in active development? I just want to know before I use on a few new projects.
> 
> Thanks in advance.

Thx for starting this conversation, which i hope will help clear things up for everyone. Have a good weekend.

**Comment by blynnc** [comment]
I am continuing to use Foundation - current version 6.5.3. I started using  Foundation when  it was pre version 4. It is the most flexible user friendly Prototype and web dev Frameowrk out there. It allows you to develop in CSS!  as well. i am also using it for really new cool projects.  My speciality is in design, Info Architecture, UI / UX - I also love to hand -code. Foundation is just perfect for me. 

It was said foundation was dying several times - I certianly don't believe that and I have continued on with much success. That being said the Zurbians and Yeti's need to communicate to their fan base - It is not cricket to leave people hanging out on a limb wondering...

I have no doubt there will be future releases, I am willing to contribute my two cents  and help when I can.

Long live Foundation. Here's to Foundation 7!!!!!!!! ....

**Comment by tarik-wifak** [comment]
Rafi mention that the framework is still alive but he told me that the forum will no longer be maintained when i have an issue to post on it ,
But we notice lack of discussion about version 7 even its roadmap is published, 
also in their advanced course Kevin claim that he left zurb.
maybe should we create a new framework on top of foundation and take the opportunity to eliminate jquery !

**Comment by JeremyEnglert** [comment]
> maybe should we create a new framework on top of foundation and take the opportunity to eliminate jquery !

I think you're underestimating how much work goes into a framework like this. I wish it were that easy. :)

But just to keep everyone looped in - discussions between the collaborators and ZURB have started back up. We're currently reviewing open PR's and will be shooting to push a final release (or maybe two) before focussing all work on F7.

We're also working on ways we can better communicate with the community.

**Comment by DanielRuf** [comment]
Hi @tarik-wifak,

The team is actively working on fixing v6 bugs, transition many things and start work on v7.

**Comment by JeremyEnglert** [comment]
> Rafi mention that the framework is still alive but he told me that the forum will no longer be maintained when i have an issue to post on it ,

A new forum is being worked on. It will use Discourse.

**Comment by tarik-wifak** [comment]
thanks @JeremyEnglert  thanks @DanielRuf 
I'm so interested in the futur of this framework i know that is too complex and more advanced but it seems that zurb will give up on the project 
I use foundation in all of my projects because all of them are both in arabic/english and other languages so the switch between rtl and ltr is easy also there is many components that doesn't exist by default in other frameworks like the  drilldown/accordion menu, vertical grid, off-canvas, abide animation and the zurb template is so powerfull but i have a lot of issues with react and scss version

**Comment by JeremyEnglert** [comment]
Thanks for the support @tarik-wifak. We're trying to address as many issues with F6 as possible while still pushing to get working on F7 as soon as possible. The more help we can get, the better and faster we can get things pushed out.

**Comment by Xavvi** [comment]
This is welcome news. We've been using Foundation as our go-to framework for around 6 or 7 years now. Would be so sad to see it go. Really excited at the thought of an F7 release!

**Comment by Baedda** [comment]
This makes me really sad. I have been a fan of Foundation since v3. I don't think that an open source only project can ever be as good as a project that is mainly maintained by a company. 

I had a feeling that Foundation is dying since there was a blog post (or something like that) that was called "Road to Foundation 7" (or something like that). And I try to remember that they wanted to release v7 at the end of 2018? But nothing happend. 

We in our company use Foundation as our primary frontend framework. Foundation was always better than Bootstrap because of its great and abstract Sass mixins. But so many parts of the framework have become overhauled in any way so we had to replace things step by step.

The breakpoint mixin has been replace by sass-mq, Orbit by Swiper, the grid will be replaced by native css grid, Equalizer by Flexbox and so on. It's sad because we earlier had an all from one hand solution but I totally understand that all of this is too much to handle by a single company.

But please don't get me wrong. The problem I have with giving Foundation to the community is, that most of the time when we had bugs with Foundation, these bugs could be pointed to a pull request from a contributor, that was not working for Zurb. A big project like this needs to be in firm hands that know all side effects pull requests can have.

**Comment by DanielRuf** [comment]
Hi @Baedda,

I can understand you. Generally there are not many who work on Foundation and still work at Turb.

I see no problem with maintainers from the community, like me. We Yetinauts still manage this and keep an eye on quality and possible side effects.

It does not mean that everyone can merge PRs.

**Comment by DanielRuf** [comment]
Hi @Baedda,

I can understand you. Generally there are not many who work on Foundation and still work at Zurb.

I see no problem with maintainers from the community, like me. We Yetinauts still manage this and keep an eye on quality and possible side effects.

It does not mean that everyone can merge PRs.

**Comment by Baedda** [comment]
I did not want to say that you are not doing a great job - because you do :) I wanted to say that it is very hard to maintain a big project like this in your freetime without getting paid for this job. That's why I'm worried that development will happen fast enough so Foundation will stay future proof.

**Comment by DanielRuf** [comment]
@Baedda We have this on our radar so stay tuned ;-)

**Comment by blynnc** [comment]
Hello,

Thank-you Daniel Ruf, I can see you are doing a ton of work.

That may be hard for you to keep up without enough support - would not like
to see you develop "Post Traumatic Stress Disorder" or "Burnout"  I second
Christopher's concern.
There has to be leadership and honest communication and steady progress
towards releases and updating of any dependencies and checking for breakage.

Many of us have been using Foundation as our goto Framework - it is lean,
mean and clean and one of the best as far as built in accessibility.

What can we do to get more coders involved?

**Comment by prembo** [comment]
This is fantastic news Foundation is still alive.  How best to manage the transition to a community driven project?  

How will the project be led / managed?  What are the main goals of v7?  In the months were development has slowed down, is there anything that competing front-end frameworks are doing that we should consider?  Any recent front-end trends / technologies that v7 can benefit from?

I would like actively and regularly contribute and can begin by working on a few of the smaller issues.  What issues are a priority?  Issues in the [6.6.0 milestone](https://github.com/zurb/foundation-sites/milestone/35)?

**Comment by dlewand691** [comment]
In case you haven't seen this, Bootstrap has released a long-term support plan. There might be some nuggets of inspiration for Foundation's future:

[https://github.com/twbs/release](https://github.com/twbs/release)

**Comment by pebbles186** [comment]
@DanielRuf do you have any news for us?
We are currently discussing how to go ahead in our enterprise applications and we would like to keep foundation if development will continue.

**Comment by DanielRuf** [comment]
@pebbles186 Foundation Sites is still actively developed and maintained but we can use any help that we can get.

**Comment by simongcc** [comment]
@DanielRuf Thanks for your great effort. Don't be frustrated.

I love foundation since a few years ago and done some projects with it because I think foundation structure is neat, less rubbish tags, class name is also intuitive. The css tools so far is also comprehensive and flexible. Although I think the gulp version's configuration can be simplified. It is overall a good project in good direction.

While I am not very familiar with working in big open source projects, I will try to share some help in simple things like bugs fixing or small issues for trial.

**Comment by DanielRuf** [comment]
Hi @simongcc,

Thank you very much. Any help is very welcome.

We plan to move away from gulp and use a full webpack config with a few plugins and scripts.

**Comment by marselgray** [comment]
I am also an avid fan and user of foundation press. I would like to help maintain this project as well.

**Comment by theblockmonkey** [comment]
Huge fan of Foundation - I hope it continues to be supported.

**Comment by DanielRuf** [comment]
Hi,

yes Foundation Sites is still actively developed.

We have already done many things to move it to the community.

You might have already noticed, that "zurb" is not the organization anymore.

We are also working on a new community / forum in the background.

We have updated and prepared the develop and master branches for v6.6 and also merged and closed many PRs and issues.

And there is a new domain which you might have already seen in the last commits: https://get.foundation

@joeworkman does a great and big job by leading the migration to a full community project where all of you become collaborators and maintainers and preparing the next release.

In general we need any help as all of this is time consuming and not easy while everyone is working for the own employer or for own clients.

How can you help? Take a look at the open isaues and PRs, create new issues for v6, provide input and ideas for v7, improve the docs, ...

If you need any help please feel free to reach out to us.

**Comment by dannycolin** [comment]
@DanielRuf Is there any plan for a survey or something similar to gather feedback for what people would like to see in v7?

**Comment by DanielRuf** [comment]
Yes, we plan to do a survey for that.

**Comment by SassNinja** [comment]
a brief update to everyone:

we're focussed now on getting v6.6.0 out asap so all of the many features & fixes in it can be used!

I've postponed everything that was scheduled for v6.6.0 (and is not close to done) to v6.7.0 so it does not block the release any longer

we're now 95% complete and I'm confident we'll reach the 100% soon
https://github.com/foundation/foundation-sites/milestone/35

since this is the first release without any influence of zurb and without our former lead developer, it takes some time to get everything done (incl. the release process)

I know you've been waiting for this release a long time and it seems there's no progress but I can assure you that we're on it!

**Comment by chstappert** [comment]
Hey together. Great work. I'm reading this thread since it came up. You reached 100% for 6.6 - that is awesome. Do you have a due date. Is there a beta or RC1 for 6.6 to test? Just setting up a new project right now.

Whats about get.foundation? Maybe I can help with some litte changes there? Is there a Website-Team?

**Comment by DanielRuf** [comment]
Hi @chstappert,

Foundation Sites v6.6.0 was released today.

I'm going to close the issue as it is resolved now.

**Comment by DanielRuf** [comment]
There will be some news regarding the website. We are still working on it.

**Comment by chstappert** [comment]
Great! Thanks a lot @DanielRuf

**Comment by Sven-WEBDESIGN** [comment]
Thanks @DanielRuf and to everyone involved that have made that possible. Kudos! :)

**Comment by tarik-wifak** [comment]
Congratulations 🥳

**Comment by joeworkman** [comment]
There is a new Foundation Community forum. I recommend that everyone here join. https://foundation.discourse.group

See you over there! 😄

**Comment by Baedda** [comment]
Good news! Thanks for your engagement!

**Comment by dlewand691** [comment]
Congratulations on the first non-Zurb release! Be sure to add any donation options to help keep support and development running.

**Comment by DieterVanWerkum** [comment]
Congratulations guys. I'm glad I checked this issue before seriously considering 'plan B(ootst . . . )'. I have no relevant developer skills to offer but will be happy to report bugs if and when.

**Comment by vesan132806** [comment]
I need help with updating the foundation press theme.I'm using version 2.10.4.I can't even open wordpress admin dashboard.can anyone please help me to find out the issue and resolve it?

**Comment by chesio** [comment]
> I need help with updating the foundation press theme.I'm using version 2.10.4.I can't even open wordpress admin dashboard.can anyone please help me to find out the issue and resolve it?

Hi @vesan132806, this repository is not for WordPress theme, but for CSS/JS framework. You want to check here: https://github.com/olefredrik/FoundationPress Note that this repo is now read only, so you won't be able to ask there for help, just search through existing issues.

Btw. if your WordPress dashboard is not available, one of your options is to connect to your website via FTP and try to disable any active plugin (or active theme) by renaming its folder. There are plenty resources online that describe this procedure. If you still are in a need of help, try asking in WordPress Support Forums: https://wordpress.org/support/forums/

**Comment by josh-atkins-10c** [comment]
Hello! Foundation is great but I've just seen this post and understand that development has stopped - thanks to everyone who has contributed to it. I'm wondering if it might be possible to add an obvious notice on the Docs website that indicates the project is read only and not under active development? I had adopted Foundation because even now it lends itself to really rapid development, but under a deadline it would have been helpful to realise upfront what the status of the project is to aid in choice of adopting or not. Cheers!

**Comment by agoradesign** [comment]
It would be really sad, if this project would die. The fact, that the development has slowed down extremely already 3 years ago, but Foundation is still the best CSS framework imho, shows impressively, how valuable this project is.

From time to time, I'm therefore trying other frameworks as well - but there wasn't a single one I've really enjoyed working with. I really don't know, why people are using Tailwind - this absolutely sucks imho. At least, it's 100% against my philosophy of writing HTML and CSS code... I tried Bulma as well, but the UX for me as developer wasn't that great. Of course I tried Bootstrap a few times - one can work with that, but there are so many small unconveniences and problems in comparison to working with Foundation, so that I'm still using it frequently :)

I'd contribute, if I could. We're a tiny agency, so money donation is nothing that I can provide. Also, I'm way more good at programming PHP than on JS for example, so contributing code to a framework like Foundation is also not really a viable option unfortunately :(

**Comment by DieterVanWerkum** [comment]
Thanks Joe for pitching in so fast. My heartrate is back to normal.

Best regards,
Dieter

**Comment by vladyslav2** [comment]
> Please refer to the Discussion Board... https://github.com/foundation/foundation-sites/discussions/12310

Does discussions been turn off? I'm not able to open your link neither discussions button on top :(

**Comment by DanielRuf** [comment]
@vladyslav2 https://github.com/foundation/foundation-sites/issues/15500#issue-2346814803

**Comment by vladyslav2** [comment]
@DanielRuf thanks, understood
perhaps link on the main page should also be updated cause it still pointing to the github discussions?
<img width="270" alt="image" src="https://github.com/user-attachments/assets/a1122fc3-2d06-4ac9-8d3f-71e5a01ca704">
