### ISSUE TITLE
zurb.com training and Lessons Url

### ISSUE THREAD

**Issue by saphemmy** [foundation/foundation-sites#11877]
## What should happen?
 Probably a 404 page or under construction
...

## What happens instead?
```
Passenger error #2
An error occurred while trying to access '/etc/httpd/htdocs/university': Cannot resolve possible symlink '/etc/httpd/htdocs/university': No such file or directory (2)
```
...

**Comment by DanielRuf** [comment]
Hi @saphemmy,

please provide all the required steps (at leat the url and screenshot of where it happens).

**Comment by saphemmy** [comment]
Example:
https://zurb.com/university/courses
https://zurb.com/university/lessons/topics/foundation
etc.

**Comment by DanielRuf** [comment]
I meant where you clicked to get to these =)

**Comment by SassNinja** [comment]
not sure whether that's all but you get there when you're on https://foundation.zurb.com/ and
- use the "tutorial" menu item in the header ("Lessons", "Courses", "Custom Training")
- click on "Training" in the footer and then click university in header/footer 

since those pages are owned by zurb only they can fix it

cc @rafibomb

**Comment by rafibomb** [comment]
I got it on my list to update, thanks!

**Comment by joeworkman** [comment]
This has been fixed.
