### ISSUE TITLE
GetYoDigits() pads with zeros when asked for more than 10 characters.  

### ISSUE THREAD

**Issue by jellisii** [foundation/foundation-sites#11883]
## What should happen?

In certain circumstances, when asking for more than 10 characters from `GetYoDigits()`, the string should continue to be random characters.

## What happens instead?

The string has 10 random characters at the front of the string, and the rest of the characters after the first 10 are 0.

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://codepen.io/jellisii/pen/OJJpwvO?editors=1011

## Context

This only appears to happen in Chrome/Chromium.  I cannot test Safari or IE easily.  Firefox behaves as expected.  My current workaround is to generate and concatenate strings of 10 characters or less.  

## Your Environment

- Foundation version(s) used: 6.5.3
- Browser(s) name and version(s): Firefox 69.0.2 on Linux, Chromium 77.0.3865.120
- Device, Operating System and version:  Ubuntu Linux 18.04

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @jellisii,

That might be because of too big values.

See https://github.com/foundation/foundation-sites/blob/develop/js/foundation.core.utils.js#L24

**Comment by DanielRuf** [comment]
https://codepen.io/DanielRuf/pen/ExxWOZz?editors=1112

https://repl.it/@DanielRuf/SoupyNavajowhitePriorities

It is an issue in v8. We do length * 36

In general this is not the right approach for random strings. I will propose a better solution. Something that is not O(^n) but O(1).

**Comment by DanielRuf** [comment]
Hi @jellisii,

That might be because of too big values.

See https://github.com/foundation/foundation-sites/blob/develop/js/foundation.core.utils.js#L24

https://codepen.io/DanielRuf/pen/ExxWOZz?editors=1112

https://repl.it/@DanielRuf/SoupyNavajowhitePriorities

It is an issue in v8. We do length * 36

In general this is not the right approach for random strings. I will propose a better solution. Something that is not O(^n) but O(1).

More details: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by DanielRuf** [comment]
Hi @jellisii,

That might be because of too big values.

See https://github.com/foundation/foundation-sites/blob/develop/js/foundation.core.utils.js#L24

https://codepen.io/DanielRuf/pen/ExxWOZz?editors=1112

https://repl.it/@DanielRuf/SoupyNavajowhitePriorities

It is an issue in v8. We do length * 36

In general this is not the right approach for random strings. I will propose a better solution. Something that is not O(36^n) but O(n) or O(1).

More details: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by DanielRuf** [comment]
Hi @jellisii,

That might be because of too big values.

See https://github.com/foundation/foundation-sites/blob/develop/js/foundation.core.utils.js#L24

https://codepen.io/DanielRuf/pen/ExxWOZz?editors=1112

https://repl.it/@DanielRuf/SoupyNavajowhitePriorities

It is an issue in v8. We do length * 36

More details: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by DanielRuf** [comment]
Hi @jellisii,

That might be because of too big values.

See https://github.com/foundation/foundation-sites/blob/develop/js/foundation.core.utils.js#L24

https://codepen.io/DanielRuf/pen/ExxWOZz?editors=1112

https://repl.it/@DanielRuf/SoupyNavajowhitePriorities

It is an issue in v8. We do 36^length.

More details: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by DanielRuf** [comment]
See https://jsperf.com/test4444 and https://codepen.io/DanielRuf/pen/pooeGxW?editors=0012

**Comment by SassNinja** [comment]
> It is an issue in v8. We do 36^length

I'm wondering why there's so much complicated math within that util regarding it's only about getting a random alphanumerical number with certain length

> See jsperf.com/test4444

really nice test 👍 
the second one (for loop) is much more clear, faster and doesn't have a problem with length > 10

I'd definitely go with it

**Comment by DanielRuf** [comment]
> I'm wondering why there's so much complicated math within that util regarding it's only about getting a random alphanumerical number with certain length

Me too. It is also interesting that this piece of code is faster on NodeJS according to the `benchmark` package compared to my proposed version.

> really nice test +1

I should have chosen a better name :D

Afaik some developer that I know might pick this up and provide a PR then =)
