### ISSUE TITLE
[sticky] Don't Work

### ISSUE THREAD

**Issue by actycrea** [foundation/foundation-sites#11932]
Since updating the foundation version from 6.5.3 to 6.6.0, this is the only problem I had.

The Sticky PLUGIN stopped working.

On the documentation page, it doesn't work either. Which can also give a hint.

https://get.foundation/sites/docs/sticky.html

- Foundation version(s) used: Foundation v6.6.0
- Browser(s) name and version(s): Chrome v78.0
- Device, Operating System and version: MacOS High Sierra

**Comment by DanielRuf** [comment]
Hi @actycrea,

thanks for reporting this. There is already an issue about this and this is fixed in the `develop` branch.

See https://github.com/foundation/foundation-sites/issues/11928 and https://github.com/foundation/foundation-sites/pull/11925

Next time please also use our issue template and check if there is an issue about this.
