### ISSUE TITLE
Tooltip is not closed on mobile when clicking outside of tooltip.

### ISSUE THREAD

**Issue by ksbek** [foundation/foundation-sites#11952]
Hello,

https://codepen.io/ZURBFoundation/pen/zwLxaY?editors=1000
This is your demo for tooltip.
On mobile(both of ios and android), tooltip is not closed when I click outside of tooltip.
Is there any solution for this?
Should I customize the source code?

**Comment by DanielRuf** [comment]
Hi @ksbek,

Please provide a codepen with your code and the current version of Foundation that you use.

**Comment by DanielRuf** [comment]
The provided codepen uses Foundation 6.3.1. So this is outdated. The docs are always for the latest release which is 6.6.1 at this time.

**Comment by ksbek** [comment]
Hi @DanielRuf , thanks for your reply.
I got that codepen url from https://get.foundation/sites/docs/tooltip.html.

I'm using foundation-rails gem(6.5.3).
I will try 6.6.1 then.
Thanks.

**Comment by ksbek** [comment]
Hello @DanielRuf ,

I tried 6.6.1, but it is same. Tooltip is not closed on mobile.
Actually, you can reproduce this issue on your tooltip documentation on mobile.
https://get.foundation/sites/docs/tooltip.html.

**Comment by DanielRuf** [comment]
Hm, can you test which was the last working version? 6.5.3?

**Comment by ksbek** [comment]
I tried both versions(6.5.3 and 6.6.1).

**Comment by DanielRuf** [comment]
> Hm, can you test which was the last working version? 6.5.3?

Ok and which version was the last working one? This would help us very much to find the problem. I do not have so much time.

**Comment by ksbek** [comment]
@DanielRuf  Sorry for bothering.
There was no working one.
On both versions, tooltip was not closed if I tapped outside of tooltip. 
I'm not sure this is bug or normal. But In my opinion, Tooltip should be closed when user taps anywhere of the screen.

**Comment by DanielRuf** [comment]
Sorry if I was not clear enough. Can you test previous releases too?

**Comment by babobski** [comment]
Confirmed it's not working with 6.5.3.
The problem is when you use data-disable-hover="true" it stays open when clicked on, but there is no way to close the tooltip.

@ksbek as a work around you can add a flag to see if there is a open tooltip. 
Then you can close the tooltip when clicked somewhere else.

```javascript
// Flag to keep track
var tooltipOpen = false;
// Switch flag when opening or closing tooltip
$('[data-tooltip]').on('show.zf.tooltip', function() {
    tooltipOpen = true;
}).on('hide.zf.tooltip', function() {
    tooltipOpen = false;
});
// If tooltip is open and the mousedown is not inside the tooltip, close the tooltip
$('body').on('mousedown', function(e) {
    if (tooltipOpen && $(e.target).parents('.tooltip').length === 0) {
        $('[data-tooltip]').foundation('hide');
    }
});
```

**Comment by ksbek** [comment]
@babobski, thank you very much. I will use your solution.

**Comment by babobski** [comment]
@ksbek I made a small update, touch wasn't supported in the fix.
Above code works with jquery versions lower than 3.
Foundation doesn't work well with jquery 3, the 'show.zf.tooltip' event is fired before/same time as the 'touchstart' event.
Causing the flag to be true when it shouldn't.
You can make it work with jquery 3 by adding a small delay when setting the tooltip open flag:

```javascript
var tooltipOpen = false,
    timeOUT;
$('[data-tooltip]').on('show.zf.tooltip', function() {
    clearTimeout(timeOUT);
    timeOUT = setTimeout(function(){    
        tooltipOpen = true;
    }, 5);
}).on('hide.zf.tooltip', function() {
    clearTimeout(timeOUT);
    tooltipOpen = false;
});

$(window).on('mousedown touchstart', function(e) {
    if (tooltipOpen && $(e.target).parents('.tooltip').length === 0) {
        $('[data-tooltip]').foundation('hide');
    }
});

```

I wanted to add a note, you shouldn't close the issue when it is not fixed in the main source code.

**Comment by SunderApps** [comment]
Using foundation-sites ^6.6.3
@babobski Your solution didn't work for me.  

1. It closes tooltips after first click because it was opened by hover.
2. This implementation overrides the default behavior of `clickOpen: true`.
3. Clicking on the tooltip doesn't keep the tooltip open for me, like this line should do: `if (tooltipOpen && $(e.target).parents('.tooltip').length === 0)`.

I couldn't figure out why #3 wasn't working and I don't need my users to be able to click on the tooltip, so I removed that part.  To fix the first two issues, though, I added some conditions to that if statement: 

`
var $target = $(e.target);
if (tooltipOpen
    && !$target.is('[data-tooltip]')
    && !$target.parents('[data-tooltip]').length) {
    $('[data-tooltip]').foundation('hide');
}
`

So the full script for jQuery 3 is:

`
var tooltipOpen = false,
    timeOUT;
$('[data-tooltip]').on('show.zf.tooltip', function() {
    clearTimeout(timeOUT);
    timeOUT = setTimeout(function(){    
        tooltipOpen = true;
    }, 5);
}).on('hide.zf.tooltip', function() {
    clearTimeout(timeOUT);
    tooltipOpen = false;
});

$(window).on('mousedown touchstart', function(e) {
    var $target = $(e.target);
    if (tooltipOpen
        && !$target.is('[data-tooltip]')
        && !$target.parents('[data-tooltip]').length) {
        $('[data-tooltip]').foundation('hide');
    }
});
`
