### ISSUE TITLE
Sticky does not stick on small screens

### ISSUE THREAD

**Issue by DarrinRobertson** [foundation/foundation-sites#11967]
## What should happen?

The sticky element should stick on small screens

## What happens instead?
The element scrolls with the page

You can test this on an existing code pen
https://codepen.io/ecabuk/pen/LYEpyew
Change the foundation css and js references to 6.6.1
Test it works on a large screen as expected. Then shrink to a small screen size and scroll down.

**Comment by DanielRuf** [comment]
Hi @DarrinRobertson,

Thanks for reporting this.

The logic was wrong in 6.6.0 and was fixed in 6.6.1. What you see is correct.

See https://github.com/foundation/foundation-sites/pull/11925

You have to set `data-sticky-on` from `medium` (default) to `small`.

See https://get.foundation/sites/docs/sticky.html#js-options and https://codepen.io/DanielRuf/pen/eYmjVKP

**Comment by DarrinRobertson** [comment]
Thanks for the reply @DanielRuf  - You are right - I never looked far enough down to see this option.
