### ISSUE TITLE
Adjust Snyk integration

### ISSUE THREAD

**Issue by DanielRuf** [foundation/foundation-sites#12037]
## Description

Currently it shows 0 vulns but there are definitely a few. We switched to GHA. What do we have to adjust @lirantal?

https://snyk.io/test/github/foundation/foundation-sites?tab=dependencies

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by lirantal** [comment]
Snyk by default will only scan and show prod dependencies and nothing in your devDependencies to lower the noise by default. You should actually connect the repo to Snyk and then from the settings UI you an toggle on to scan for devDepndencies too.

If you use the Snyk CLI in your build then `snyk test --dev` will do it.
Strongly recommended however to integrate the GitHub app so that you get:
1. automatic pull request for security fixes
2. automatic dependency upgrades (a la greenkeeper)
3. break the build when a new PR introduces vulnerabilities in new/existing dependencies

--

Here is what a snyk scan (and the website scan you used) shows by default, with no devDeps scanning:
![image](https://user-images.githubusercontent.com/316371/77882831-80ba1500-726a-11ea-849c-234509949d5f.png)

Here is a snyk scan when you also scan for devDeps:
![image](https://user-images.githubusercontent.com/316371/77882859-93cce500-726a-11ea-995b-17b0680392c0.png)
( and many more vulns and upgrade advice that I cut from the screenshot)

Hope it helps!

--

@DanielRuf what vulnerabilities did GHA show you? if they were with regards to production dependencies that we didn't find I'm curious to learn which exactly.

**Comment by joeworkman** [comment]
@DanielRuf to my knowledge all of this is setup already. We have automatic PRs coming in. I have added you to the Snyk Organization so that you can tweak any settings that you may want. From my perspective though, it looks to be working.

**Comment by DanielRuf** [comment]
Seems to be correctly configured so far. Closing.
