### ISSUE TITLE
is Foundation dead?

### ISSUE THREAD

**Issue by rahiyansafz** [foundation/foundation-sites#12191]
Is Foundation really Dead?
where is everyone? where is @rafibomb and @kball ?
I only see @DanielRuf to reply and contribute and solve and do all the things..
What happened to the Zurb? Could you please tell?

**Comment by DanielRuf** [comment]
Please see https://github.com/foundation/foundation-sites/issues/11767 and other relevant issues.

ZURB gave the project to the maintainers, contributors and the community a while ago. The new lead since then is @joeworkman who coordinates everything (releases and so on).

Most of the previous ZURB people who worked on Foundation do not work there anymore afaik.
ZURB themself are focusing on their new and current products (Helio for example).

**Comment by DanielRuf** [comment]
Personally I am not an active contributor and mainainter anymore since the end of last year as I focus and invest my time in my daily work, also due to the lack of Foundation projects at the new workplace.

**Comment by rahiyansafz** [comment]
zurb just abandoned foundation!!!!!? why? i dont think helio is as popular as foundation were, are...
Can you tell at least this that the foundation will be developing in the future??? 
our company uses every single project in foundation. we love it so much.

hope for your reply and a huge thanks to you.

**Comment by DanielRuf** [comment]
They didn't abandon it. It is a community-led opensource project for much longer. Maintainers and contributors like Nicolas Coden are not directly from Zurb.

**Comment by DanielRuf** [comment]
> Can you tell at least this that the foundation will be developing in the future???

It is not dead.

> our company uses every single project in foundation. we love it so much.

Contributions including pull requests are very welcome.

**Comment by rahiyansafz** [comment]
thanks a lot @DanielRuf 
i miss the old active hyped Foundation.
Let's hope for the best

**Comment by rahiyansafz** [comment]
who was the lead then? who left zurb????

**Comment by DanielRuf** [comment]
Current lead is @joeworkman. I do not know any details about ZURB as I did not work there and joined as collaborator and became part of the maintainer team.

Please see #11767. At the moment there is not much more that I can tell. The transition was done many months ago and since then issues and pull requests are still answered. There is currently not much to do and I have to focus on projects at work.

**Comment by iamkevinmccarthy** [comment]
@DanielRuf My team and I have a new PHP-based web app we're working on. We've yet to choose a CSS framework but I tend to promote Foundation as I've found it enjoyable to work with. I also tend wish to avoid Bootstrap at all costs. So, if you were starting a project from scratch, knowing that—for argument's sake—the development & future of Foundation has the potential to become stagnant, what frameworks would you consider taking a look at that are actively in development?

**Comment by joeworkman** [comment]
I definitely plan on making headway on Foundation 7 this year. Please refer to https://github.com/foundation/foundation-sites/issues/11847#issuecomment-763125885

**Comment by rahiyansafz** [comment]
> I definitely plan on making headway on Foundation 7 this year. Please refer to [#11847 (comment)](https://github.com/foundation/foundation-sites/issues/11847#issuecomment-763125885)

We LOVE Foundation. thanks @joeworkman

**Comment by maietta** [comment]
I've been a user of Foundation for Sites since version 2.x, way back in the day.

Up until recently, I've always used a pre-compiled version of Foundation for Sites. After shifting to a continuous deployment / continuous integration model for website development, I was in the right position to finally adopt the SASS method. This has given me a new lease on development life. I'm able to easily pick and choose just what I need and tweak anything I need tweaked.

Foundation is far from dead. As long as browses continue to work with 6.x, we will be good. I am still hopeful to see what's in store for version 7 and I wish I was a bit more versed in CSS and had more time because I would love nothing more than to actively work on the next version. Gotta keep working on paid gigs....

I don't think Foundation is dead. Just because a project doesn't get a lot of commit activity doesn't mean it's dead. There doesn't seem to be reason for lots of commit activity given how good the framework is.
