### ISSUE TITLE
Weird space in Full Reveal Safari iOS 15

### ISSUE THREAD

**Issue by JuveJaimes** [foundation/foundation-sites#12330]
## What should happen?

When you use a full size reveal in mobile devices the size should be 100% of the screen.

## What happens instead?

There is a weird space in the bottom of the screen when you open a full size reveal in mobile. 

## Possible Solution

Not sure about what is causing this issue but I think it is related with the fixed position.

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. Enter to https://get.foundation/sites/docs/reveal.html in an iPhone device with iOS 15.
2. Go to Full-screen section.
3. Open reveal with "Click me for a full-screen modal" Button.
4. See extra space at the bottom of the screen.

## Context

This issue is affecting my project because part of the content shown in a modal is cut by this weird empty space.
I attached two images one using iOS 14 and other using iOS 15.

## Your Environment

- Foundation version(s) used: 6.7.4
- Browser(s) name and version(s):  Safari 
- Device, Operating System and version:  iPhone 11 Pro iOS, v15.0
- Using BrowserStack, but issue was found originally in a real iPhone 11.

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.
![iOS14](https://user-images.githubusercontent.com/8901872/141531157-37ff95a3-e1c9-4bbe-bfd7-a30e3ca03268.PNG)
![iOS15](https://user-images.githubusercontent.com/8901872/141531159-7e445866-3826-459e-9d64-3b9c924629e1.PNG)

**Comment by joeworkman** [comment]
If you extract just the full screen Reveal, it works... 

https://codepen.io/joeworkman/full/70ccdae4f35072dbf53cf8bdad67be4d

**Comment by jeremylind** [comment]
@joeworkman, I'm not sure what you mean by extracting the full screen Reveal, but I think the issue might be with how Safari calculates 100% height of fixed elements. With a full screen Reveal, the html element receives `position: fixed;` and `height: 100%;` styling. Safari iOS 15 calculates that to the height of the viewport with the full app address bar displaying, even if the summary address bar with a smaller height is displaying. It also doesn't seem to adjust the height when switching between the address bars. I think your codepen doesn't display this issue because the page is shorter than the viewport. Without scrolling down, Safari never switches to the summary address bar.

**Comment by Discostu36** [comment]
I think this issue should be reopened. All reveals on mobile have problems when the browser UI is at the bottom on the page and in a collapsed state when the reveal is opened. This leads to the problem mentioned above and additionally something that looks like a white overlay at the bottom of the page (in reality it seems that the document doesn't use the whole window height). Happens on Firefox and Safari. I don't know if Chrome has an option for UI at the bottom.

![photo_2023-04-04_17-55-36](https://user-images.githubusercontent.com/30999326/229849191-bac53f01-9731-4bbf-a26d-8d8ae3ad1501.jpg)

![photo_2023-04-04_17-55-38](https://user-images.githubusercontent.com/30999326/229849206-42768ed8-1477-4e48-9db8-2731c6d27180.jpg)

Please keep in mind that the white area at the bottom is not part of the reveal. It is also white when the reveal is black.
