### ISSUE TITLE
the changelog for 6.8.0 should mention the end of support for node-sass

### ISSUE THREAD

**Issue by stof** [foundation/foundation-sites#12581]
https://github.com/foundation/foundation-sites/commit/3a4eecb168273a509dfe9989977790edd25dbdb2 introduces usages of `@use` in the Sass files, which is not supported by node-sass (because it is not implemented by libsass but only by dart-sass).

While this move is fine (dart-sass is the modern implementation of Sass), I think it would deserve being highlighted explicitly in the readme.

**Comment by alexeych** [comment]
Yep, and SASS versions support should be clearly stated in project description.
Foundation Sites 6.8.0 and Motion UI 2.0.4 don't support node-sass.

For example, "Zurb template" will fail to compile, because it [requires](https://github.com/foundation/foundation-zurb-template/blob/master/package.json) the latest version of foundation-sites, but installs node-sass as well.

I tried to update foundation-sites and motion-ui in my boilerplate and didn't expect such breaking change in minor version.

**Comment by Currey** [comment]
@alexeych have you found a work around? I still regularly use the foundation-zurb-template, but now can't work out how to get it to install without loads issues (which I'm guessing are due to node-sass?).

**Comment by stof** [comment]
@Currey either use `sass` instead of `node-sass` or downgrade foundation-sites to 6.7. That's the workaround.

**Comment by erutan** [comment]
foundation-zurb-template should really get an updated package.json. :)

I'm just keep it pinned < 6.8 for simplicity.

`"foundation-sites": "~6.7.5",`

**Comment by stof** [comment]
@erutan updating the template is indeed a good move as tracked in #12588.

However, to resolve the current issue, I'm expected a maintainer to update the changelog for 6.8.0

**Comment by erutan** [comment]
Yeah, that's why I made a different issue. :)
