### ISSUE TITLE
Full menu rework

### ISSUE THREAD

**Issue by kball** [foundation/foundation-sites#9421]
We want to clean up the way menus work to make them much easier to customize, make them more consistently accessible, and easier to work with.

Opening this to collect related code snippets, prs, issues, and conversations.

Some initial items of interest are: 

- https://github.com/zurb/foundation-sites/pull/9283 (temporarily reverted in https://github.com/zurb/foundation-sites/pull/9420). 

- the discussion in https://github.com/zurb/foundation-sites/pull/9381

... others? 

(cc @zurb/yetinauts @sethkane)

**Comment by andycochran** [comment]
#7235

**Comment by brettsmason** [comment]
So from my point of view, the main issues are:

- the default `.menu` class is too opinionated - things like padding should be left to modifier classes and specific component classes (dropdown, accordion etc) to add this sort of styling
- The specificity of the selectors makes it really difficult to override styles

A fairly brief attempt at seperating this can be seen here: http://brettmason.co.uk/menus/all-menus.html
This would allow classes to be combined, without them all overwriding eachothers styles.

**Comment by ncoden** [comment]
My thoughts about menu : Your menu should with a structure exactly like `.menu > li > a` and with the default style. If you want something else, you're damn.

Things to avoid for the new menu:
- selecting elements by their tag
- mixing graphical and structural properties
- high specificity

**Comment by andycochran** [comment]
A few other gathered thoughts… 

- #8504 Menu item height should be the same as button height. 

- How do we handle button/menu item radius in v6.4? There's been a lot of debate about radius on group vs radius on each button. #9031 "fixed" #8447 for v6.3. But I think the framework could/should support both cases. See also this [Codepen](http://codepen.io/andycochran/pen/reJRro) which also mentions the issues with menus/button groups wrapping to multiple lines. 

- #8239 Generate menu color classes from the palette. No need to have both `.stacked-for-small.button-group` _and_ `.vertical.medium-horizontal.menu`.

**Comment by JeremyEnglert** [comment]
A big part of Foundation 6 was cutting down on the amount of variables in the settings.scss file, however, navigation items are a great example of where having "a lot" of settings greatly improves ease of use. 

As others have mentioned, it becomes quite the pain to override specific styles in a menu because they are very specific - to make this even more challenging, it's often hard to find the specific classes to target using Dev Tools as the classes are added dynamically via JS.

The downside to this is that the navigation components are not strictly just navigation components anymore. For example, an accordion can be used anywhere and the way a navigational accordion and an accordion in content would be styled may be quite different.

One idea would be to create additional settings variables specific to navigation items wrapped in a top-bar. This allows users to style a top-bar accordion without clashing with their regular accordion styles.

**Comment by andycochran** [comment]
A couple issues with menu arrows: 
http://codepen.io/andycochran/pen/oBxXqq

I propose that `$dropdownmenu-arrows`/`$accordionmenu-arrows`/etc. can be set to either `left`, `right`, `true`, or `false`. 

If the arrow is to the left of the text, you get this:
![image](https://cloud.githubusercontent.com/assets/409279/21862936/5c13a1d4-d809-11e6-94da-d389f3d2bc4f.png)

…instead of this: 
![image](https://cloud.githubusercontent.com/assets/409279/21862900/2e15e774-d809-11e6-870f-e82717f18892.png)

**Comment by JeremyEnglert** [comment]
Is this something we're trying to do in Foundation 6 or 7?

I would think since it's a full rewrite, it would best be saved for 7. 

Beyond the grid, my assumption would be that menu/navigation components are the most used component in the framework.

**Comment by rafibomb** [comment]
In theory - It wouldn't cause a breaking change - so we would feel good about it as a feature for 6.4 for example.

**Comment by rafibomb** [comment]
@andycochran Maybe the solution is in flexbox, where you would have each menu item be with: auto and then space-around to spread them apart.

@brettsmason Has a demo and proposal to convert the menu's back to inline-block, in which we can address this use case as well.

**Comment by IllusionPerdu** [comment]
The menu dropdown have beug with the touchscreen : #9652 you can probably fix this during your rework

**Comment by IamManchanda** [comment]
was just reading @rafibomb comment,
> Maybe the solution is in flexbox, where you would have each menu item be with: auto and then space-around to spread them apart.

For me .... the flexbox is the way to go specially for navbar

Eg.... Boostrap's Alpha 5 to 6 transition ( flexbox transition )

> As mentioned in our last release, the Alpha 5 navbar was a little half baked. This time around, we’re completely baked. No, but seriously, the navbar has been rewritten to provide better built-in responsive behaviors and improved layout customization thanks to our move to flexbox.

**Comment by JeremyEnglert** [comment]
This is an interesting issue, as many other button and menu related issues reference it. But at this point in V6 - I'm assuming we aren't going to re-write the menus, right?

**Comment by ncoden** [comment]
@JeremyEnglert If we go for a SMACSS architecture, yes we will.
