### ISSUE TITLE
Element disappears with show-large-only on "large" screen

### ISSUE THREAD

**Issue by nonpcnpc** [foundation/foundation-sites#9663]
So the foundation comes with three grids: small, medium large. So I would expect that small works from zero to X width, medium works from X to Y width and large works from Y up to infinity. But when I use the show-for-large-only class the element disappears if the screen/window width goes above about 930px which means that either there are missing xlarge/xxlarge grids or the large grid is capped at certain width. This is not a behavior I would expect to see.

**Comment by ncoden** [comment]
Hi @ivanjaros.

You issue make me see three problems:
- [Media Queries docs ](http://foundation.zurb.com/sites/docs/media-queries.html) is out-of-date.
- A lot of code in `@mixin show-for-only` ([scss/components/_visibility.scss:18](https://github.com/ncoden/foundation-sites/blob/bfeccde3d79d9b8fda9138bd23b8ddb5cac5a811/scss/components/_visibility.scss#L18)) is duplicated and could be replaced by `@mixin breakpoint`. @gakimball removed it at 96f3fee0f186800b6b17d794a0e098839b96b61b and I do not understand why.
- The bug: we are using the `$breakpoints` map (map of all breakpoints, with `xlarge` and `xxlarge` by default)  to get breakpoint values, and not `$breakpoint-classes` (list of breakpoints used to generate classes). So `show-for-large-only` is generated with the assumption there is a `xlarge` breakpoint after it, and has a max limit of `xlarge - 1`.

Because I never thought about this before, I am afraid this 3rd problem is not only present on visibility classes, but on many other Foundation components.

**Comment by ChaseIndustries** [comment]
@ivanjaros Why don't you just use the `.show-for-large` class or if you are using SCSS remove the `xlarge` and `xxlarge` breakpoints in your `settings.scss`? This did the trick for me.

It looks like @gakimball removed that code because `@mixin breakpoint` is inclusive of the breakpoint its passed and in order to accurately give the element a `display:none` property,  you need to target the viewports 'around' the breakpoint.

**Comment by colin-marshall** [comment]
@ncoden can you please revisit this issue when you have time? Thanks!

**Comment by DanielRuf** [comment]
Closing as this issue has no codepen and this depends on the setup.
